### ISSUE TITLE
Does Twitter handle need @ or not?

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/drips-app#20]
Not clear whether the twitter username should include @ or not. Sometimes there is an @ symbol prefilled in the field.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/4406983/144140095-e7f987de-0531-41b1-a03c-fddb0ca2e5f9.png">

**Comment by bordumb** [comment]
A user actually saw a bug related to this topic.

I've filed a detailed issue below, so maybe we can close this one in favor of that one:
https://github.com/radicle-dev/drips-app/issues/76

**Comment by brandonhaslegs** [comment]
I think this was solved. The placeholder doesn't have an @ so I assume the @ is not required. 
![image](https://user-images.githubusercontent.com/4406983/150968116-3e87db99-019c-4166-bb14-59ff14002cc7.png)
