### ISSUE TITLE
Cumulative Revenue Should Not Be "0" If a Subscription Has Been Bought

### ISSUE THREAD

**Issue by gh0stwheel** [radicle-dev/drips-app#45]
Reported by: @cloudhead

Priority: High

Currently, if a subscription/membership has been purchased for a Community, but the end of the current cycle hasn't come yet, the "cumulative revenue" will show as "0" on the Community detail page. This is very confusing for end users, who may suspect a scam or bug. Cumulative revenue should probably be updated to show the revenue that the Community owner/creator is currently expected to receive, even if they can't collect it until the end of the cycle.

**Comment by evvvritt** [comment]
Added
