### ISSUE TITLE
Remove Proposals toggle unless a community has Snapshot voting enabled

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/drips-app#71]
If a user hasn't added Snapshot voting, that doesn't mean it's coming soon! This wording should be more inclusive of people who don't ever intend to set up snapshot voting.

![image](https://user-images.githubusercontent.com/4406983/149826131-7cbe3da7-ec87-48db-ae5a-460a08e6a4bd.png)

**Comment by evvvritt** [comment]
Snapshot hasn't been finalized but I think it's sensible that it wouldn't be required. That said, do you think we should still revise this text?

**Comment by brandonhaslegs** [comment]
Yeah I think if you want to advertise that Snapshot voting is coming to communities, there must be a better place to put that (landing page, or community creation flow maybe). Otherwise if a community never sets up snapshot voting they will always have this text on their community.

**Comment by brandonhaslegs** [comment]
I think if Snapshot voting is not set up, this section shouldn't be here. It should just be Benefits. Once the community adds snapshot voting, then the Benefits/Proposals toggle appears.
