### ISSUE TITLE
Suggestion - Add "Join" directly to homepage  

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app#77]
## Overview 

Currently, to join a Community, this is the work a user must do:
1. Visit [app.drips.network](https://app.drips.network/explore)
2. Scroll down to the Community section
3. Click "View"
4. Click "Join"
5. Click "Join" again
6. Click "Allow"
7. Go through Metamask confirmation

## Proposal

I'd like to propose stripping the clicks needed as much as humanly possible.

I think it's possible to get rid of Step 3 above by doing this to the front page:

![image](https://user-images.githubusercontent.com/3743841/150655818-1bcb6df1-c856-4249-ab9d-ff430723a15f.png)

## Motivation

I am very confident this will lower the friction involved in what is currently a 7+ step process.

I've worked for consumer apps as a data scientist designing and analyzing A/B tests for the past 7 years. For the past 4 years, I've worked specifically on paid subscription apps.

A common issue that has _always_ shown the same results is:

> Making users do work is _**the**_ direct cause of them them using apps less

I've seen this in 100% of the > 100 A/B tests that I've helped run. 

If I imagine starting the "Join" process in 1-click from the homepage, it becomes really seamless; much more approachable and less esoteric. Just the fact that I can get it started with 1-click helps me forget about all the other steps involved (at least I got started in 1-click!). What I've seen with A/B testing is that each time a user has to navigate to a new page, it sort of adds to the level of "wonkiness" if that makes sense.

**Comment by evvvritt** [comment]
Sensible! Will queue it

**Comment by evvvritt** [comment]
Added to the new UI :) https://app.drips.network
